### ISSUE TITLE
Service crashes in "dev" mode when JSON is updated

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/VAMDataService#3]
Updates to the tracked JSON file will crash the server:
```
/Users/mfuroyama/software/VAM/VAMDataService/src/websocket.js:35
        const { rpcs, data, ...rest } = value;
                                        ^

ReferenceError: value is not defined
    at WebSocketClass.update (/Users/mfuroyama/software/VAM/VAMDataService/src/websocket.js:35:41)
    at emitOne (events.js:116:13)
    at DevModeDynamoDB.emit (events.js:211:7)
    at newSessions.reduce (/Users/mfuroyama/software/VAM/VAMDataService/src/dynamodb.js:134:22)
    at Array.reduce (<anonymous>)
    at StatWatcher.DevModeDynamoDB.fs.watchFile (/Users/mfuroyama/software/VAM/VAMDataService/src/dynamodb.js:132:25)
    at emitTwo (events.js:126:13)
    at StatWatcher.emit (events.js:214:7)
    at StatWatcher._handle.onchange (fs.js:1452:10)
```

**Comment by mfuroyama** [comment]
Had the wrong variable name in the update function. Switched out to fix the crash
